"""Core enums, models, and type definitions for Phase 37 Communication Infrastructure."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid


class CommunicationType(str, Enum):
    """Explicit categories for communication and notifications."""

    SYSTEM = "SYSTEM"
    OPERATIONAL = "OPERATIONAL"
    SECURITY = "SECURITY"
    APPROVAL = "APPROVAL"
    WORKFLOW = "WORKFLOW"
    SALES = "SALES"
    CLIENT = "CLIENT"
    PROJECT = "PROJECT"
    SUPPORT = "SUPPORT"
    BILLING = "BILLING"
    AI = "AI"
    MARKETING = "MARKETING"


class NotificationPriority(str, Enum):
    """Priority level determining routing, quiet-hours bypass, and escalation."""

    CRITICAL = "CRITICAL"  # Security alerts, critical incidents - bypasses quiet hours
    HIGH = "HIGH"          # Approvals, client actions, UAT
    NORMAL = "NORMAL"      # Task assignments, milestones, updates
    LOW = "LOW"            # General analytics, background summaries


class DeliveryChannel(str, Enum):
    """Supported delivery channels."""

    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    PUSH = "PUSH"
    CLIENT_PORTAL = "CLIENT_PORTAL"
    MESSAGING = "MESSAGING"  # WhatsApp, SMS, etc.


class DeliveryStatus(str, Enum):
    """Lifecycle status of a notification or communication delivery."""

    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    DELIVERED = "DELIVERED"
    READ = "READ"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class InboxState(str, Enum):
    """State of an item inside the Unified Inbox."""

    UNREAD = "UNREAD"
    READ = "READ"
    ARCHIVED = "ARCHIVED"
    SNOOZED = "SNOOZED"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    COMPLETED = "COMPLETED"


class MessageVisibility(str, Enum):
    """Visibility scope for messages and notes."""

    INTERNAL = "INTERNAL"            # Internal team members only (never visible to client)
    CLIENT_VISIBLE = "CLIENT_VISIBLE"  # Visible to client and internal team
    SYSTEM = "SYSTEM"                # Generated by system/workflow
    RESTRICTED = "RESTRICTED"        # Security/Admin only


class ConversationType(str, Enum):
    """Classification of conversation threads."""

    INTERNAL = "INTERNAL"
    CLIENT = "CLIENT"
    SUPPORT = "SUPPORT"
    SALES = "SALES"
    PROJECT = "PROJECT"
    SYSTEM = "SYSTEM"


@dataclass
class DeliveryPayload:
    """Normalized payload envelope for channel dispatchers."""

    recipient_id: str
    tenant_id: str
    subject: str
    body: str
    channel: DeliveryChannel
    priority: NotificationPriority = NotificationPriority.NORMAL
    category: CommunicationType = CommunicationType.OPERATIONAL
    action_url: Optional[str] = None
    action_type: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    deduplication_key: Optional[str] = None
