"""API router for Phase 31 Business Insights & Recommendations."""

from typing import Any, Dict, List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_db
from app.repositories.analytics import AnalyticsRepository
from app.services.analytics import AnalyticsService
from app.schemas.analytics import (
    InsightResponse,
    InsightReviewRequest,
    RecommendationResponse,
    RecommendationReviewRequest,
)
from app.models.analytics import InsightStatus

router = APIRouter(prefix="/insights", tags=["insights"])


def get_analytics_service(session: AsyncSession = Depends(get_db)) -> AnalyticsService:
    repo = AnalyticsRepository(session)
    return AnalyticsService(repo)


@router.get("", response_model=List[InsightResponse])
async def list_insights(
    tenant_id: str = "default_tenant",
    category: Optional[str] = None,
    status: Optional[str] = None,
    limit: int = 50,
    offset: int = 0,
    service: AnalyticsService = Depends(get_analytics_service),
) -> Any:
    """List empirical organizational insights with audit-proof evidence."""
    return await service.repo.list_insights(tenant_id, category=category, status=status, limit=limit, offset=offset)


@router.get("/recommendations", response_model=List[RecommendationResponse])
async def list_recommendations(
    tenant_id: str = "default_tenant",
    status: Optional[str] = None,
    workflow: Optional[str] = None,
    service: AnalyticsService = Depends(get_analytics_service),
) -> Any:
    """List reviewable recommendations generated by the learning engine."""
    return await service.repo.list_recommendations(tenant_id, status=status, workflow=workflow)


@router.get("/{insight_id}", response_model=InsightResponse)
async def get_insight_details(
    insight_id: str,
    service: AnalyticsService = Depends(get_analytics_service),
) -> Any:
    """Get full details and evidence items for a business insight."""
    insight = await service.repo.get_insight(insight_id)
    if not insight:
        raise HTTPException(status_code=404, detail=f"Insight '{insight_id}' not found.")
    return insight


@router.post("/{insight_id}/review", response_model=InsightResponse)
async def review_insight(
    insight_id: str,
    req: InsightReviewRequest,
    service: AnalyticsService = Depends(get_analytics_service),
) -> Any:
    """Human review of a discovered insight (ACCEPT, REJECT, ARCHIVE, REVIEW)."""
    status_map = {
        "ACCEPT": InsightStatus.ACCEPTED,
        "REJECT": InsightStatus.REJECTED,
        "ARCHIVE": InsightStatus.ARCHIVED,
        "REVIEW": InsightStatus.REVIEWED,
    }
    target_status = status_map.get(req.action.upper(), InsightStatus.REVIEWED)
    updated = await service.repo.update_insight_status(insight_id, target_status, reviewed_by=req.reviewed_by)
    if not updated:
        raise HTTPException(status_code=404, detail=f"Insight '{insight_id}' not found.")
    return updated


@router.post("/recommendations/{rec_id}/review", response_model=RecommendationResponse)
async def review_recommendation(
    rec_id: str,
    req: RecommendationReviewRequest,
    service: AnalyticsService = Depends(get_analytics_service),
) -> Any:
    """Human decision on a recommendation. Never automatically mutates production policies."""
    updated = await service.repo.review_recommendation(
        rec_id=rec_id,
        reviewer=req.reviewer,
        action=req.action,
        notes=req.notes,
        policy_impact=req.policy_impact,
    )
    if not updated:
        raise HTTPException(status_code=404, detail=f"Recommendation '{rec_id}' not found.")
    return updated
