"""Pydantic data schemas for Personalization Agent inputs, profile, claims, and output drafts."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class VerifiedSignal(BaseModel):
    """Factually verified signal extracted from research, audit, score, qualification, or CRM."""
    source_type: str  # RESEARCH, AUDIT, SCORE, RECOMMENDATION, QUALIFICATION, CRM
    signal_name: str
    description: str
    evidence_id: Optional[str] = None
    confidence: str = "HIGH"  # HIGH, MEDIUM, LOW


class BusinessNeedMapping(BaseModel):
    """Mapping observed verified signals to potential customer communication needs."""
    observed_gap: str
    potential_need: str
    relevant_service_slug: Optional[str] = None
    evidence_ids: List[str] = Field(default_factory=list)


class CommunicationAngle(BaseModel):
    """Structured communication angle focused on a verified business opportunity."""
    angle_type: str  # WEBSITE_IMPROVEMENT, LEAD_CAPTURE, BOOKING, AUTOMATION, CUSTOM_SYSTEM, AI_SUPPORT, DIGITAL_PRESENCE, CUSTOMER_COMMUNICATION
    title: str
    problem_statement: str
    value_proposition: str
    evidence_ids: List[str] = Field(default_factory=list)
    confidence: str = "HIGH"


class ClaimItem(BaseModel):
    """Individual claim contained in a draft with factual support classification."""
    statement: str
    classification: str = "VERIFIED"  # VERIFIED, INFERRED, GENERAL
    is_supported: bool = True
    evidence_ids: List[str] = Field(default_factory=list)
    risk_notes: Optional[str] = None


class PersonalizationProfile(BaseModel):
    """Structured personalization profile forming the evidence-backed foundation for outreach."""
    business_summary: str
    audience_context: Optional[str] = None
    verified_signals: List[VerifiedSignal] = Field(default_factory=list)
    business_needs: List[BusinessNeedMapping] = Field(default_factory=list)
    relevant_services: List[Dict[str, Any]] = Field(default_factory=list)
    value_opportunities: List[str] = Field(default_factory=list)
    primary_angle: CommunicationAngle
    supporting_angles: List[CommunicationAngle] = Field(default_factory=list)
    evidence: List[Dict[str, Any]] = Field(default_factory=list)
    confidence: str = "HIGH"  # HIGH, MEDIUM, LOW
    warnings: List[str] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)
    prohibited_claims: List[str] = Field(default_factory=list)


class OutreachDraftPayload(BaseModel):
    """Structured outreach draft generated by the Personalization Agent."""
    channel: str = "EMAIL"  # EMAIL, WHATSAPP, SMS, LINKEDIN, OTHER
    tone: str = "PROFESSIONAL"  # PROFESSIONAL, FRIENDLY, CONCISE, CONSULTATIVE, LOCAL_BUSINESS
    language: str = "en"
    personalization_depth: str = "STANDARD"  # LIGHT, STANDARD, DEEP
    objective: str = "INTRODUCE_SERVICE"
    subject: Optional[str] = None
    body: str
    claims: List[ClaimItem] = Field(default_factory=list)
    risk_level: str = "LOW"  # LOW, MEDIUM, HIGH, BLOCKED
    outreach_readiness: str = "READY"  # READY, NEEDS_MANUAL_REVIEW, NOT_RECOMMENDED, OUTREACH_BLOCKED
    approval_status: str = "PENDING_APPROVAL"  # PENDING_APPROVAL, APPROVED, REJECTED
    version: int = 1
    content_hash: Optional[str] = None


class PersonalizationRequest(BaseModel):
    """Input payload for Personalization Agent execution."""
    lead_id: str
    channel: str = "EMAIL"
    tone: str = "PROFESSIONAL"
    language: str = "en"
    personalization_depth: str = "STANDARD"
    objective: str = "INTRODUCE_SERVICE"
    service_focus: Optional[str] = None
