"""
Base Domain Types, Enums, and Shared Schemas for Phase 55:
Unified Product & Innovation Intelligence, Idea Discovery, Validation & R&D Platform.
"""

from enum import Enum
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field


class InnovationStage(str, Enum):
    DRAFT = "DRAFT"
    DISCOVERY = "DISCOVERY"
    RESEARCH = "RESEARCH"
    VALIDATION = "VALIDATION"
    EXPERIMENTATION = "EXPERIMENTATION"
    EVALUATION = "EVALUATION"
    APPROVED = "APPROVED"
    DEVELOPMENT = "DEVELOPMENT"
    LAUNCH = "LAUNCH"
    MONITORING = "MONITORING"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class HorizonLevel(str, Enum):
    H1 = "H1"  # Core business improvement
    H2 = "H2"  # Adjacent expansion
    H3 = "H3"  # Transformational new markets
    HORIZON_1_CORE = "H1"
    HORIZON_2_ADJACENT = "H2"
    HORIZON_3_TRANSFORMATIONAL = "H3"


class IdeaSource(str, Enum):
    HUMAN = "HUMAN"
    AI_WORKER = "AI_WORKER"
    CLIENT = "CLIENT"
    SUPPORT = "SUPPORT"
    RESEARCH = "RESEARCH"
    MARKET_TREND = "MARKET_TREND"
    COMPETITOR = "COMPETITOR"
    SECURITY = "SECURITY"
    STRATEGIC_OBJECTIVE = "STRATEGIC_OBJECTIVE"


class ProblemStatus(str, Enum):
    OBSERVED = "OBSERVED"
    RESEARCHING = "RESEARCHING"
    VALIDATED = "VALIDATED"
    UNVALIDATED = "UNVALIDATED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class IdeaStatus(str, Enum):
    IDEA = "IDEA"
    SHORTLISTED = "SHORTLISTED"
    RESEARCHING = "RESEARCHING"
    VALIDATING = "VALIDATING"
    EXPERIMENTING = "EXPERIMENTING"
    PROMISING = "PROMISING"
    REJECTED = "REJECTED"
    DEFERRED = "DEFERRED"
    APPROVED = "APPROVED"


class HypothesisStatus(str, Enum):
    DRAFTED = "DRAFTED"
    FORMULATED = "FORMULATED"
    TESTING = "TESTING"
    VALIDATED = "VALIDATED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class ExperimentType(str, Enum):
    EXPLORATORY = "EXPLORATORY"
    DESCRIPTIVE = "DESCRIPTIVE"
    COMPARATIVE = "COMPARATIVE"
    AB_TEST = "AB_TEST"
    PILOT = "PILOT"
    PROTOTYPE = "PROTOTYPE"
    PRICING = "PRICING"
    SURVEY = "SURVEY"


class ExperimentStatus(str, Enum):
    DESIGNED = "DESIGNED"
    APPROVED = "APPROVED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class StatisticalOutcome(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    INCONCLUSIVE = "INCONCLUSIVE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class GateStage(str, Enum):
    GATE_0_IDEA = "GATE_0_IDEA"
    GATE_1_PROBLEM = "GATE_1_PROBLEM"
    GATE_1_PROBLEM_VALIDATION = "GATE_1_PROBLEM"
    GATE_2_OPPORTUNITY = "GATE_2_OPPORTUNITY"
    GATE_2_OPPORTUNITY_VALIDATION = "GATE_2_OPPORTUNITY"
    GATE_3_SOLUTION = "GATE_3_SOLUTION"
    GATE_3_SOLUTION_VALIDATION = "GATE_3_SOLUTION"
    GATE_4_BUSINESS = "GATE_4_BUSINESS"
    GATE_4_BUSINESS_VALIDATION = "GATE_4_BUSINESS"
    GATE_5_MVP = "GATE_5_MVP"
    GATE_5_MVP_APPROVAL = "GATE_5_MVP"
    GATE_6_LAUNCH = "GATE_6_LAUNCH"
    GATE_6_LAUNCH_APPROVAL = "GATE_6_LAUNCH"
    GATE_7_SCALE_PIVOT = "GATE_7_SCALE_PIVOT"
    GATE_7_SCALE_PIVOT_STOP = "GATE_7_SCALE_PIVOT"


class GateDecision(str, Enum):
    PROCEED = "PROCEED"
    PIVOT = "PIVOT"
    PAUSE = "PAUSE"
    STOP = "STOP"
    REVISE_EVIDENCE = "REVISE_EVIDENCE"
    PENDING = "PENDING"


class PivotAction(str, Enum):
    CONTINUE = "CONTINUE"
    PIVOT_CUSTOMER = "PIVOT_CUSTOMER"
    CUSTOMER_SEGMENT_PIVOT = "PIVOT_CUSTOMER"
    PIVOT_PROBLEM = "PIVOT_PROBLEM"
    PIVOT_VALUE_PROP = "PIVOT_VALUE_PROP"
    VALUE_PROPOSITION_PIVOT = "PIVOT_VALUE_PROP"
    PIVOT_BUSINESS_MODEL = "PIVOT_BUSINESS_MODEL"
    BUSINESS_MODEL_PIVOT = "PIVOT_BUSINESS_MODEL"
    PIVOT_TECHNOLOGY = "PIVOT_TECHNOLOGY"
    PAUSE = "PAUSE"
    STOP = "STOP"
