"""Business Glossary service for Phase 65."""

from typing import Any, Dict, List, Optional
import uuid
from datetime import datetime, timezone


class GlossaryService:
    """Manages authoritative business terms, definitions, synonyms, and linked metrics."""

    def __init__(self):
        self._terms: Dict[str, Dict[str, Any]] = {}
        self._seed_default_glossary()

    def _seed_default_glossary(self):
        seeds = [
            ("Customer", "An individual or organization that has entered into an active commercial agreement.", "Customers", ["Client", "Account"], ["active_customers_count", "mrr"]),
            ("Monthly Recurring Revenue (MRR)", "The normalized monthly value of recurring subscription revenue.", "Finance", ["MRR", "Recurring Run Rate"], ["mrr", "arr", "net_expansion"]),
            ("Customer Lifetime Value (LTV)", "The projected total revenue generated by a customer over their entire relationship.", "Finance", ["LTV", "CLV"], ["ltv", "cac_ratio"]),
            ("Qualified Lead", "A prospective account that meets explicit budget, authority, need, and timeline criteria.", "Sales", ["SQL", "Opportunity Candidate"], ["qualification_rate"]),
            ("Sprint Velocity", "The number of story points or work units delivered per engineering iteration.", "Engineering", ["Velocity", "Delivery Throughput"], ["cycle_time", "dora_speed"]),
        ]
        for name, defn, domain, syns, metrics in seeds:
            tid = f"term_{name.lower().replace(' ', '_').replace('(', '').replace(')', '')}"
            self._terms[tid] = {
                "id": tid,
                "tenant_id": "default_tenant",
                "term_name": name,
                "definition": defn,
                "domain": domain,
                "owner": "governance@uzaii.com",
                "synonyms": syns,
                "related_metrics": metrics,
                "status": "CERTIFIED",
                "created_at": datetime.now(timezone.utc).isoformat(),
            }

    def create_term(self, data: Dict[str, Any], tenant_id: str = "default_tenant") -> Dict[str, Any]:
        d = dict(data)
        if "term" in d and "term_name" not in d:
            d["term_name"] = d["term"]
        res = self.add_term(d, tenant_id)
        res["term"] = res["term_name"]
        return res

    def add_term(self, data: Dict[str, Any], tenant_id: str = "default_tenant") -> Dict[str, Any]:
        term_id = data.get("id") or f"term_{uuid.uuid4().hex[:12]}"
        record = {
            "id": term_id,
            "tenant_id": tenant_id,
            "term_name": data.get("term_name", "New Term"),
            "definition": data.get("definition", ""),
            "domain": data.get("domain", "General"),
            "owner": data.get("owner", "governance@uzaii.com"),
            "synonyms": data.get("synonyms", []),
            "related_metrics": data.get("related_metrics", []),
            "status": data.get("status", "CERTIFIED"),
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        self._terms[term_id] = record
        return record

    def list_terms(self, domain: Optional[str] = None, tenant_id: str = "default_tenant") -> List[Dict[str, Any]]:
        terms = [t for t in self._terms.values() if t.get("tenant_id") == tenant_id]
        if domain:
            terms = [t for t in terms if t.get("domain", "").lower() == domain.lower()]
        return terms

    def get_term(self, term_id: str, tenant_id: str = "default_tenant") -> Optional[Dict[str, Any]]:
        t = self._terms.get(term_id)
        if t and t.get("tenant_id") == tenant_id:
            return t
        return None
